#! /bin/bash
# Copyright (C) 2018 Merspieler, merspieler _at_ airmail.cc
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

first=1
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
	-h|--help)
		echo "usage: clear-cache-files <project> [OPTIONS]"
		echo "Cleares cache files created by osm2city."
		echo ""
		echo "OPTIONS"
		echo "  -h, --help	Shows this help and exit"
		exit 0
	;;

	*)
		if [ $first == "1" ]; then
			project="$1"
			shift # past project
			first=0
		else
                	echo "Unknown option $key"
                	exit 1
		fi
        ;;
esac
done

if [ -z "$project" ]; then
	echo "No project was given. See clear-cache-files -h for details"
	exit 1
fi

rm projects/$project/*.pkl
