#! /bin/bash
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
        -p|--project)
	        project="$2"
		shift # past argument
		shift # past value
        ;;

	-h|--help)
		echo "usage: clear-cache-files -p <project> [OPTIONS]"
		echo "Cleares cache files created by osm2city."
		echo ""
		echo "OPTIONS"
		echo "  -p, --project	Mandatory, project name which you want to clear of chache files"
		echo "  -h, --help	Shows this help and exit"
		exit 0
	;;

        *)
                echo "Unknown option $key"
                exit 1
        ;;
esac
done

if [ -z "$project" ]; then
	echo "Option -p <project> is mandatory"
	exit 1
fi

rm projects/$project/*.pkl
