#! /bin/bash
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
	-h|--help)
		echo "usage: create-venv [OPTIONS]"
		echo "Creates a python virtual environment and installs all needed packages in"
		echo "the venv."
		echo ""
		echo "OPTIONS"
		echo "  -h, --help      Shows this help and exit"
		exit 0
	;;

	*)
		echo "Unknown option $key"
		exit 1
	;;
esac
done

python3 -m venv venv/
source venv/bin/activate
pip install descartes matplotlib networkx numpy pillow pyproj scipy shapely psycopg2-binary
if [ $? == 1 ]; then
	echo "pip had problems installing some packages"
	echo "Please make sure that all of the following packages are installed in the venv"
	echo "descartes"
	echo "matplotlib"
	echo "networkx"
	echo "numpy"
	echo "pillow"
	echo "pyproj"
	echo "scipy"
	echo "shapely"
	echo "psycopg2-binary"
	echo "NOTE: use 'source venv/bin/activate' before you install the packages"
fi
