#! /bin/bash
# Copyright (C) 2018-2019 Merspieler, merspieler _at_ airmail.cc
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
        -h|--help)
                echo "usage: update-programs [OPTIONS]"
                echo "Updates easy-osm2city, osm2city and osm2city-data."
                echo ""
                echo "OPTIONS"
                echo "  -h, --help      Shows this help and exit"
                exit 0
        ;;

        *)
                echo "Unknown option $key"
                exit 1
        ;;
esac
done

echo "Updateing easy-osm2city..."
git pull --rebase

wd=$(pwd)

if [ -f scripts/README.md ]; then
	echo "Updating scripts..."
	cd scripts
	git pull --rebase
fi

cd $wd

echo "Updateing osm2city..."
cd osm2city
git pull --rebase

echo "Updating osm2city-data..."
cd ../osm2city-data
git pull --rebase

echo "Updating venv..."
cd ../
source venv/bin/activate
pip install -r osm2city/requirements.txt
